name: raxmlng
description: RAxML-NG is a phylogenetic tree inference tool which uses maximum-likelihood
  (ML) optimality criterion.
keywords:
  - phylogeny
  - newick
  - maximum likelihood
tools:
  - raxmlng:
      description: RAxML-NG is a phylogenetic tree inference tool which uses maximum-likelihood
        (ML) optimality criterion.
      homepage: https://github.com/amkozlov/raxml-ng
      documentation: https://github.com/amkozlov/raxml-ng/wiki
      tool_dev_url: https://github.com/amkozlov/raxml-ng
      doi: 10.1093/bioinformatics/btz305
      license: ["GPL v2-or-later"]
      identifier: ""
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information (e.g. [ id:'sample1' ])
    - alignment:
        type: file
        description: A FASTA format multiple sequence alignment file
        pattern: "*.{fasta,fas,fa,mfa}"
    - model:
        type: string
        description: The substitution model to use for the phylogenetic inference

output:
  - phylogeny:
      - meta:
          type: map
          description: Groovy Map containing sample information
          pattern: "*.{raxml.bestTree}"
      - "*.raxml.bestTree":
          type: map
          description: Groovy Map containing sample information
          pattern: "*.{raxml.bestTree}"
  - phylogeny_bootstrapped:
      - meta:
          type: map
          description: Groovy Map containing sample information
          pattern: "*.{raxml.support}"
          optional: true
      - "*.raxml.support":
          type: map
          description: Groovy Map containing sample information
          pattern: "*.{raxml.support}"
          optional: true
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@avantonder"
  - "@aunderwo"
maintainers:
  - "@avantonder"
  - "@aunderwo"
